name: test frontend
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: change directory
        working-directory: ./frontend

      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm run test